#!/bin/bash
#
# THIS FILE IS MANAGED BY PUPPET!
#
# chkconfig: 2345 80 20
# description: uWSGI

# Source function library.
. /etc/rc.d/init.d/functions

exec=/srv/oclubs/pyenv/versions/python-pyenv/bin/uwsgi
prog=uwsgi
config=/etc/uwsgi/uwsgi.ini
lockfile=/var/lock/subsys/uwsgi

workdir=/srv/oclubs

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6

    cd $workdir && action "Starting $prog" $exec --daemonize --ini /etc/uwsgi/uwsgi.ini
    retval=$?
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    action "Stopping $prog" $exec --stop /var/run/uwsgi/uwsgi.pid
    retval=$?
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

brutal-shutdown() {
    echo -n "Killing $prog"
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    action "Reloading $prog" $exec --reload /var/run/uwsgi/uwsgi.pid
    return $?
}

force-reload() {
    action "Reloading $prog" kill -TERM "$(cat /var/run/uwsgi/uwsgi.pid)"
    return $?
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    kill)
        rh_status_q || exit 0
        brutal-shutdown
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 0
        $1
        ;;
    force-reload)
        reload
        restart
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    status)
        rh_status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|kill|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?